---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: tke-auth-controller
  name: tke-auth-controller
  namespace: tke
spec:
  replicas: {{ .Replicas }}
  selector:
    matchLabels:
      app: tke-auth-controller
  template:
    metadata:
      labels:
        app: tke-auth-controller
    spec:
      containers:
        - name: tke-auth-controller
          image: {{ .Image }}
          args:
            - -C=/app/conf/tke-auth-controller.toml
          volumeMounts:
            - name: certs-volume
              mountPath: /app/certs
            - name: tke-auth-controller-volume
              mountPath: /app/conf
          ports:
            - containerPort: 9458
          livenessProbe:
            httpGet:
              port: 9458
              path: /healthz
              scheme: HTTPS
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
      volumes:
        - name: certs-volume
          configMap:
            name: certs
        - name: tke-auth-controller-volume
          configMap:
            name: tke-auth-controller
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tke-auth-controller
  namespace: tke
data:
  tke-auth-controller.toml: |
    [secure_serving]
    tls_cert_file = "/app/certs/server.crt"
    tls_private_key_file = "/app/certs/server.key"

    [client]

      [client.auth]
      api_server = "https://tke-auth-api"
      api_server_client_config = "/app/conf/tke-auth-config.yaml"

    [features]
      category_path = "/app/auth/category.json"
      policy_path = "/app/auth/policy.json"
      tenant_admin = "{{ .AdminUsername }}"
      tenant_admin_secret = "{{ .AdminPassword }}"

  tke-auth-config.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: tke
        cluster:
          certificate-authority: /app/certs/ca.crt
          server: https://tke-auth-api
    users:
      - name: admin-cert
        user:
          client-certificate: /app/certs/admin.crt
          client-key: /app/certs/admin.key
    current-context: tke
    contexts:
      - context:
          cluster: tke
          user: admin-cert
        name: tke

