---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.platform.tkestack.io
spec:
  caBundle: {{ .Values.api.caCrt | b64enc }}
  group: platform.tkestack.io
  groupPriorityMinimum: 1000
  service:
    name: tke-platform-api
    namespace: tke
    port: 443
  version: v1
  versionPriority: 5
---
kind: Service
apiVersion: v1
metadata:
  name: tke-platform-api
  namespace: tke
  annotations:
    tke.prometheus.io/scrape: "true"
    prometheus.io/scheme: https
spec:
  selector:
    app: tke-platform-api
  ports:
    - protocol: TCP
      port: 443
      targetPort: 9443
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: tke-platform-api
  name: tke-platform-api
  namespace: tke
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: tke-platform-api
  template:
    metadata:
      labels:
        app: tke-platform-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - tke-platform-api
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
        - name: tke-platform-api
          image: {{ .Values.api.image }}
          args:
            - -C=/app/conf/tke-platform-api.toml
{{- if .Values.api.enableAudit }}
            - --audit-policy-file=/app/conf/audit-policy.yaml
            - --audit-webhook-config-file=/app/conf/audit-api-client-config.yaml
{{- end }}
          volumeMounts:
            - name: certs-volume
              mountPath: /app/certs
            - name: tke-platform-api-volume
              mountPath: /app/conf
            - name: provider-volume
              mountPath: /app/provider/baremetal
            - name: provider-config-volume
              mountPath: /app/provider/baremetal/conf/
            - name: docker-volume
              mountPath: /app/provider/baremetal/conf/docker/
            - name: kubelet-volume
              mountPath: /app/provider/baremetal/conf/kubelet/
            - name: kubeadm-volume
              mountPath: /app/provider/baremetal/conf/kubeadm/
            - name: gpu-manifests-volume
              mountPath: /app/provider/baremetal/manifests/gpu/
            - name: csi-operator-manifests-volume
              mountPath: /app/provider/baremetal/manifests/csi-operator/
            - name: keepalived-manifests-volume
              mountPath: /app/provider/baremetal/manifests/keepalived/
            - name: metrics-server-manifests-volume
              mountPath: /app/provider/baremetal/manifests/metrics-server/
          ports:
            - containerPort: 9443
          readinessProbe:
            httpGet:
              port: 9443
              path: /healthz/ping
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 9443
              path: /healthz
              scheme: HTTPS
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              cpu: 150m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: certs-volume
          configMap:
            name: certs
        - name: tke-platform-api-volume
          configMap:
            name: tke-platform-api
        - name: provider-volume
          emptyDir: {}
        - name: provider-config-volume
          configMap:
            name: provider-config
        - name: docker-volume
          configMap:
            name: docker
        - name: kubelet-volume
          configMap:
            name: kubelet
        - name: kubeadm-volume
          configMap:
            name: kubeadm
        - name: gpu-manifests-volume
          configMap:
            name: gpu-manifests
        - name: csi-operator-manifests-volume
          configMap:
            name: csi-operator-manifests
        - name: keepalived-manifests-volume
          configMap:
            name: keepalived-manifests
        - name: metrics-server-manifests-volume
          configMap:
            name: metrics-server-manifests
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tke-platform-api
  namespace: tke
data:
  tke-platform-api.toml: |
    [secure_serving]
    tls_cert_file = "/app/certs/server.crt"
    tls_private_key_file = "/app/certs/server.key"

    [etcd]
    servers = [
      "https://etcd.kube-system:2379"
    ]
    cafile = "/app/certs/etcd-ca.crt"
    certfile = "/app/certs/etcd.crt"
    keyfile = "/app/certs/etcd.key"

    [generic]
    external_hostname = "tke-platform-api"
    external_port = 443

    [authentication]
    token_auth_file = "/app/certs/token.csv"
    client_ca_file = "/app/certs/ca.crt"

      [authentication.oidc]
{{- if .Values.api.enableAuth }}
      client_id = "default"
      issuer_url = "https://tke-auth-api/oidc"
      external_issuer_url = "https://tke-auth-api/oidc"
      ca_file = "/app/certs/ca.crt"
      username_prefix ="-"
      username_claim = "name"
      groups_claim = "groups"
      tenantid_claim = "federated_claims"
{{- else }}
      client_id = {{ .Values.api.oIDCClientID }}
      issuer_url = {{ .Values.api.oIDCIssuerURL }}
  {{- if .Values.api.useOIDCCA }}
      ca_file = "/app/certs/oidc-ca.crt"
  {{- end}}
{{- end }}

{{- if .Values.api.enableAuth }}
      [authentication.webhook]
      config_file = "/app/conf/tke-authn-webhook.yaml"
{{- end }}

      [authentication.requestheader]
      client_ca_file = "/app/certs/front-proxy-ca.crt"
      username_headers = "X-Remote-User"
      group_headers = "X-Remote-Group"
      extra_headers_prefix = "X-Remote-Extra-"

  tke-platform-config.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: tke
        cluster:
          certificate-authority: /app/certs/ca.crt
          server: https://tke-platform-api
    users:
      - name: admin-cert
        user:
          client-certificate: /app/certs/admin.crt
          client-key: /app/certs/admin.key
    current-context: tke
    contexts:
      - context:
          cluster: tke
          user: admin-cert
        name: tke

  tke-authn-webhook.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: tke
        cluster:
          certificate-authority: /app/certs/ca.crt
          server: https://tke-auth-api/auth/authn
    users:
      - name: admin-cert
        user:
          client-certificate: /app/certs/admin.crt
          client-key: /app/certs/admin.key
    current-context: tke
    contexts:
    - context:
        cluster: tke
        user: admin-cert
      name: tke

  tke-authz-webhook.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: tke
        cluster:
          certificate-authority: /app/certs/ca.crt
          server: https://tke-auth-api/auth/authz
    users:
      - name: admin-cert
        user:
          client-certificate: /app/certs/admin.crt
          client-key: /app/certs/admin.key
    current-context: tke
    contexts:
    - context:
        cluster: tke
        user: admin-cert
      name: tke

{{- if .Values.api.enableAudit }}
  audit-policy.yaml: |
    apiVersion: audit.k8s.io/v1
    kind: Policy
    omitStages:
    - "RequestReceived"
    - "ResponseStarted"
    rules:
    - level: None
      resources:
      - group: "platform.tkestack.io"
        resources: ["configmaps", "*/status"]
    - level: RequestResponse
      verbs: ["create", "update", "patch", "delete", "deletecollection"]

  audit-api-client-config.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: tke
        cluster:
          insecure-skip-tls-verify: true
          server: https://tke-audit-api/apis/audit.tkestack.io/v1/events/sink/control-plane
    current-context: tke
    contexts:
      - context:
          cluster: tke
        name: tke

{{- end }}
