---
# tasks file for tke-mgr
- include: init-tke-cfg.yml
- include: init-keepalived.yml 
- include: manager-tke-node.yml
- include: remove-cluster.yml
- include: tke-gateway-mgr.yml
- include: master-mgr.yml
